build:
  version: "1.0"

accounts:
  message: "Welcome to Accounts Microservice related prod APIs"
  contactDetails:
    name: "orang prod - Product Owner"
    email: "prod_team@microservice.com"
  onCallSupport:
    - 1234567890
    - 1234567890
