build:
  version: "2.0"

accounts:
  message: "Welcome to Accounts Microservice related QA APIs"
  contactDetails:
    name: "orang qa - QA Lead"
    email: "qa_team@microservice.com"
  onCallSupport:
    - 1234567890
    - 1234567890
