build:
    version: "2.0"

cards:
    message: "Welcome to Loans Microservice related QA APIs"
    contactDetails:
        name: "orang qa - QA Leader"
        email: "qa_team@microservice.com"
    onCallSupport:
        - 1234567890
        - 9876543210