build:
    version: "1.0"

cards:
    message: "Welcome to Cards Microservice related prod APIs"
    contactDetails:
        name: "orang prod - Product Owner"
        email: "prod_team@microservice.com"
    onCallSupport:
        - 1234567890
        - 9876543210