build:
    version: "3.0"

loans:
    message: "Welcome to Loans Microservice local APIs"
    contactDetails:
        name: "Mimay"
        email: "fachritaufann@gmail.com"
    onCallSupport:
        - 1234567890
        - 9876543210
