spring:
    application:
        name: "configserver"
    profiles:
        active: native
    cloud:
        config:
            server:
                native:
                    search-locations: "classpath:/config"
    rabbitmq:
        host: "localhost"
        port: 5672
        username: "guest"
        password: "guest"

management:
    endpoints:
        web:
            exposure:
                include: "*"
    health:
        readiness-state:
            enabled: true
        liveness-state:
            enabled: true
    endpoint:
        health:
            probes:
                enabled: true

encrypt:
    key: "F1GH1023HLAB120MBG1K2K"

server:
    port: 8071